### ISSUE TITLE
Dataset issues

### ISSUE THREAD

**Issue by BAI233133** [brambozz/medical-diffusion-on-a-budget#1]
Hello, how do I process the data set for this project, especially the text inversion image part? How do I process the data so that I can train myself? And what is the role of stylegan3 here?

**Comment by brambozz** [comment]
Hi, thanks for your interest in the project!

In terms of data processing, you need to generate 512x512 RGB images to train with the AUTOMATIC1111 web ui. I followed the instructions [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Textual-Inversion).

I will add code later (probably in the week of May 6 due to vacation) for some of the use cases in the paper.

The paper recently got accepted for [MIDL2024](https://2024.midl.io/), an updated pre-print will be available on arxiv soon. In the updated version of the paper, we used StyleGAN3 as a baseline comparison model.
