### ISSUE TITLE
Dataset labeling problem

### ISSUE THREAD

**Issue by BAI233133** [brambozz/medical-diffusion-on-a-budget#2]
I used the automatic annotation plug-in, which generated irrelevant text annotations for me, which made my training extremely difficult. I would like to know how you process the annotated data for embedding training, and some related training parameters.What I want to train is CT images like the one below
![2-19-2](https://github.com/brambozz/medical-diffusion-on-a-budget/assets/76684965/770090ea-0571-4ff5-aea7-25c92234956d)

**Comment by brambozz** [comment]
Hi again!

Indeed, the automatic labeller is not much use, because it is trained on natural images. It won't generate useful annotations for medical images.

What I did was overwrite the textual inversion templates ([this file for example](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/textual_inversion_templates/subject.txt)) and only put `[name]` there.

If you have meaningful annotations for your images it could of course be useful.

Hope that helps!

**Comment by brambozz** [comment]
Hey! Just to confirm `coconut_test.txt` looks like:

```
[name]
```

Since you can generate with my trained embeddings, something must be going wrong during training. Although I would also check inference parameters, like the CFG scale and copy the parameters from my paper. The image you show looks like it was generated with relatively high CFG scale (5+), whereas I ended up using 2.

One final idea I have: I think if you don't re-initialize the embedding file it will continue training from the previous version. So just to be sure, I would delete the `chexpert_mature_fruit` file in the embeddings folder, and do a new training session with the correct template.

The reason is that to me it looks like the embedding was trained while it used the filenames (chexpert_mature_fruit_something) as text prompt, because the generated images look somewhat like avocado/pear to me :)

**Comment by brambozz** [comment]
Happy to hear it!

Could you perhaps share what were the things you had to do to solve your problems (for future people reading this issue)?
